on:
  issue_comment:
    types: [created]

name: Update PR
jobs:
  update-pr:
    name: Update PR (Merge or Rebase)
    if: github.event.issue.pull_request != '' && (contains(github.event.comment.body, '/rebase') || contains(github.event.comment.body, '/merge'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Backfill commit history up to 3 months
        # Format is YYYY-MM-DD
        run: |
          FETCH_START=`gdate -d "-3 months" +"%Y-%m-%d"`
          git fetch --shallow-since=$FETCH_START origin master
        
      - name: Update PR ('${{ github.event.comment.body }}')
        uses: zacsweers/rebase@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMENT: ${{ github.event.comment.body }}
          # Optional, specify if you want it to hide or delete the merge comment
          GITHUB_COMMENT_ID: ${{ github.event.comment.node_id }}
