on:
  pull_request:
    types: [labeled]
name: Automatic Merge
jobs:
  merge:
    name: Merge
    if: contains(github.event.pull_request.labels.*.name, 'merge-pls') || contains(github.event.pull_request.labels.*.name, 'rebase-pls')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Automatic Rebase
        uses: zacsweers/rebase@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUB_LABEL: ${{ github.event.label.name }}
          GITHUB_LABEL_ID: ${{ github.event.label.node_id }}
          GITHUB_PR_ID: ${{ github.event.pull_request.node_id }}
